# Generated by Django 3.0.3 on 2020-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200720_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='noted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
