# Generated by Django 3.0.3 on 2020-09-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200916_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
