# Generated by Django 3.0.3 on 2020-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
