# Generated by Django 3.0.3 on 2020-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200730_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='color', max_length=120),
        ),
    ]
